# Justification (docs/license-policy.md rule 3): keep our deliberately tiny
# dependency set current. Actions updates arrive as PRs that re-pin to new
# immutable SHAs; Go module updates cover the declared module graph.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
