package beelzebub

import (
	"fmt"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

// EmitConfig builds one complete AegisMesh configuration document from every
// translated sensor result. It never enables security relaxations: privileged
// ports or public binds surface as validation failures for the operator to
// decide on deliberately.
func EmitConfig(results []*Result) ([]byte, error) {
	sensors := make([]map[string]any, 0, len(results))
	taken := map[string]bool{}
	for _, r := range results {
		if r == nil || r.Sensor == nil {
			continue
		}
		id, _ := r.Sensor["id"].(string)
		base := id
		for n := 2; taken[id]; n++ {
			id = fmt.Sprintf("%s-%d", base, n)
		}
		if id != base {
			r.Notes = append(r.Notes, "sensor id "+strconv.Quote(base)+" duplicated an earlier import; renamed to "+strconv.Quote(id))
			r.Sensor["id"] = id
		}
		taken[id] = true
		sensors = append(sensors, r.Sensor)
	}
	if len(sensors) == 0 {
		return nil, fmt.Errorf("%w: no service document produced a translatable sensor", errImport)
	}
	doc := map[string]any{
		"api_version": "aegismesh.io/v1alpha1",
		"runtime": map[string]any{
			"instance_name": "migrated-from-beelzebub",
		},
		"sensors": sensors,
	}
	b, err := yaml.Marshal(doc)
	if err != nil {
		return nil, fmt.Errorf("%w: emit: %v", errImport, err)
	}
	header := "# Generated by 'aegismesh migrate beelzebub' (dry-run report reviewed).\n" +
		"# Review all rules and personas before running; defaults stay loopback-only.\n"
	return append([]byte(header), b...), nil
}

// EmittedName derives the output filename for a source file, preserving the
// source stem and marking provenance.
func EmittedName(source string) string {
	base := filepath.Base(source)
	ext := filepath.Ext(base)
	stem := strings.TrimSuffix(base, ext)
	if stem == "" || stem == "." {
		stem = "config"
	}
	return stem + ".aegismesh.yaml"
}
