package config

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
)

//go:embed assets/demo.yaml
var demoConfig []byte

// Scaffold writes a demo configuration plus a short README into dir. It
// refuses to overwrite existing files unless force is true. The generated
// config contains only synthetic data and safe loopback defaults.
func Scaffold(dir string, force bool) ([]string, error) {
	cfgPath := filepath.Join(dir, "mesh.yaml")
	readmePath := filepath.Join(dir, "README.md")

	for _, p := range []string{cfgPath, readmePath} {
		if _, err := os.Stat(p); err == nil && !force {
			return nil, fmt.Errorf("refusing to overwrite existing %s (pass --force to overwrite)", p)
		}
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("create directory %s: %v", dir, err)
	}
	if err := os.WriteFile(cfgPath, demoConfig, 0o644); err != nil { //nolint:gosec // world-readable config is intentional
		return nil, fmt.Errorf("write %s: %v", cfgPath, err)
	}
	if err := os.WriteFile(readmePath, []byte(scaffoldReadme), 0o644); err != nil {
		return nil, fmt.Errorf("write %s: %v", readmePath, err)
	}
	return []string{cfgPath, readmePath}, nil
}

const scaffoldReadme = `# AegisMesh local workspace

Generated by ` + "`aegismesh init`" + `. Everything here is synthetic.

- ` + "`mesh.yaml`" + ` — sensor configuration (loopback bind, unprivileged ports).
- ` + "`data/`" + ` — created on first run; holds the JSONL evidence store.

Try it:

    aegismesh doctor --config mesh.yaml
    aegismesh validate --config mesh.yaml
    aegismesh run --config mesh.yaml

Then trigger events (second terminal):

    curl -s -o /dev/null -w '%{http_code}\n' http://127.0.0.1:8081/admin/login
    printf 'PING\n' | nc 127.0.0.1 6399
    curl -s -X POST http://127.0.0.1:8090/mcp -H 'Content-Type: application/json' \
      -d '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"canary:prod-db-export","arguments":{"database":"prod"}}}'

Inspect evidence:

    aegismesh inspect list --data-dir ./data
`
