apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegismesh.fullname" . }}
  labels:
    {{- include "aegismesh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ default "TCP" .protocol }}
    {{- end }}
  selector:
    {{- include "aegismesh.selectorLabels" . | nindent 4 }}
